#!/bin/bash

set -e

EXIT_CODE=0

echo
echo 'INFO: Start radosgw...'
docker-compose up > logs/compose.log &

echo
echo 'INFO: Wait for RGW to become available'
attempts=1
until out=$(curl --max-time 1 --head --fail http://127.0.0.1:8080 2>&1); do
  if [ ${attempts} -eq 120 ]; then
    echo "ERROR: Max attempts reached"
    echo "$out"
    exit 1
  fi

  printf '.'
  attempts=$((attempts+1))
  sleep 1
done

echo
echo
echo 'INFO: Runtime information'
docker-compose exec -T ceph ceph --version

echo
echo 'INFO: Run test script...'
if ! ruby ./script.rb 2>&1; then
  echo
  echo "ERR: Script failed!"
  EXIT_CODE=1
fi

top="$(docker-compose top || true)"
if [ -z "$top" ]; then
  echo
  echo "INFO: container not running anymore."
  echo "$top"
  EXIT_CODE=1
fi

exit $EXIT_CODE
