#!/bin/bash

set -e

EXIT_CODE=0

echo
echo 'INFO: Start radosgw...'
docker-compose up -d

echo
echo -n 'INFO: Wait for RGW to become available'
until curl --output /dev/null --silent --head --fail http://127.0.0.1:8080; do
  printf '.'
  sleep 5
done

echo
echo 'INFO: Runtime information'
docker-compose exec -T ceph ceph --version

echo
echo 'INFO: Run script...'
if ! ruby ./script.rb 2>&1; then
  echo
  echo "ERR: Script failed!"
  EXIT_CODE=1
fi

top="$(docker-compose top || true)"
if [ -z "$top" ]; then
  echo
  echo "INFO: container not running anymore."
  echo "$top"
  EXIT_CODE=1
fi

echo "INFO: Last lines from RGW log output"
tail -n200 logs/client.rgw.test.log

exit $EXIT_CODE
