name: test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1"

jobs:
  test:
    name: ${{ matrix.tag }}
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        tag:
          - latest
          - latest-devel
          - latest-quincy
          - latest-quincy-devel
          - latest-pacific
          - latest-pacific-devel

    env:
      CEPH_TAG: ${{ matrix.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Install aws-sdk-s3 ruby gem
        run: sudo gem install aws-sdk-s3
      - name: Execute test script
        run: ./test
      - name: Collect compose logs
        run: cat logs/compose.log
        if: success() || failure()
      - name: Collect RadosGW log
        run: cat logs/client.rgw.test.log
        if: success() || failure()
      - name: Upload RadosGW log as build artifact
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: ${{ matrix.tag }}-rgw-log
          path: logs/client.rgw.*.log
