name: test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1"

jobs:
  test:
    name: ${{ matrix.tag }}
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        tag:
          - latest
          - latest-devel
          - latest-quincy
          - latest-quincy-devel
          - latest-pacific
          - latest-pacific-devel

    env:
      CEPH_TAG: ${{ matrix.tag }}

    steps:
      - uses: actions/checkout@master
      - run: sudo gem install aws-sdk-s3
      - run: ./test
      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: rgw-log
          path: logs/client.rgw.*.log
